apiVersion: azmonitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: zipline-hub-monitor
  namespace: zipline-system
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: orchestration-hub  # adjust selector based on your hub service labels
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s

---
{{ if .Values.global.deploy_fetcher }}
apiVersion: azmonitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: zipline-fetcher-monitor
  namespace: zipline-system
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: fetcher  # adjust selector based on your fetcher service labels
  podMetricsEndpoints:
    - port: chronon-prom
      path: /metrics
      interval: 30s
    - port: vertx-prom
      path: /metrics
      interval: 30s
{{ end }}